name: "Akhil Labudubariki's Blog"
title: "Akhil's Blog"
description: "Akhil Labudubariki"

url: 'https://akhil.xyz' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site
plugins:
  - 'jekyll-paginate'
  - 'octopress-codeblock'
  - 'jekyll-feed'
  - 'liquid_reading_time'
  - 'jekyll-seo-tag'
  - 'jekyll-analytics'
  - 'jekyll-sitemap'

sass:
    style: :compressed
    sass_dir: assets/css/

favicon:
  source: assets/images/favicon.png

author: 'Akhil Labudubariki'

disqus-id: 'akhil-lb'

twitter:
  card: summary

jekyll_analytics:
  GoogleAnalytics:
    id: UA-102871020-1
